In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import tejapi
import yfinance as yf
import cufflinks as cf
import h5py
pd.options.mode.chained_assignment = None
from pandas_datareader import data
tejapi.ApiConfig.api_key ="gJmwWQMfIUIuyCKhYsQD10Aa0wIQ8f"

TypeError: 'module' object is not callable

,Date,Open,High,Low,Close,Adj Close,Volume
0,2008-05-21,63.430000,63.430000,63.430000,63.430000,63.430000,0.0
1,2008-05-22,63.439999,63.439999,63.439999,63.439999,63.439999,0.0
2,2008-05-23,62.230000,62.230000,62.230000,62.230000,62.230000,0.0
3,2008-05-26,61.630001,61.630001,61.630001,61.630001,61.630001,0.0
4,2008-05-27,62.139999,62.139999,62.139999,62.139999,62.139999,0.0
...,...,...,...,...,...,...,...
3197,2021-05-14,128.500000,130.250000,127.849998,128.949997,128.949997,15214683.0
3198,2021-05-17,125.199997,128.800003,124.699997,126.500000,126.500000,31603624.0
3199,2021-05-18,128.350006,132.300003,128.000000,132.300003,132.300003,16272929.0
3200,2021-05-19,132.199997,132.649994,130.500000,131.399994,131.399994,16920497.0
3201,2021-05-20,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
def RSIcalc(asset):
    df['MA200'] =  df['Adj Close'].rolling(window=200).mean()
    df['price change'] = df ['Adj Close'].pct_change()
    df['Upmove'] = df['price change'].apply(lambda x :x if x > 0 else 0)
    df['Downmove'] = df['price change'].apply(lambda x : abs(x) if x < 0 else 0)
    df['avg Up'] =df['Upmove'].ewm(span=19).mean() 
    df['avg Down'] =df['Downmove'].ewm(span=19).mean() 
    df = df.dropna()
    df['RS'] = df['avg Up']/df['avg Down']
    df['RSI'] = df['RS'].apply(lambda x:100-(100/(x+1)))
    df.loc[(df['Adj Close'] > df['MA200']) &(df['RSI'] <30),'Buy'] = 'Yes'
    df.loc[(df['Adj Close'] < df['MA200']) |(df['RSI'] >30),'Buy'] = 'NO'
    return df 
RSIcalc(tw0050)

UnboundLocalError: local variable 'df' referenced before assignment